version: '3'
services:
  php-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "docker-qst-php-web"
    working_dir: "/var/www/html"
    volumes:
      - "./php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "../src:/var/www/html"
    ports:
      - "9000:9000"
    networks:
      - docker-qst-network
  web:
    image: nginx:stable-alpine
    container_name: "docker-qst-web"
    working_dir: "/var/www/html"
    ports:
      - "9085:80"
    volumes:
      - "../src:/var/www/html"
      - "./nginx/web/logs:/var/log/nginx"
      - "./nginx/web/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php-web
      - mysql
      - redis
    links:
      - mysql
      - redis
    networks:
      - docker-qst-network
  mysql:
    image: mysql:8.0.25
    container_name: "docker-qst-mysql"
    restart: unless-stopped
    tty: true
    ports:
      - "9306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./mysql/init:/docker-entrypoint-initdb.d"

    environment:
      MYSQL_ROOT_PASSWORD: "docker"
    networks:
      - docker-qst-network
  redis:
    image: redis
    container_name: "docker-qst-redis"
    restart: always
    ports:
      - "9379:6379"
    volumes:
      - "./redis/data:/data"
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
    networks:
      - docker-qst-network
networks:
  docker-qst-network:
